### ISSUE TITLE
cannot export to java

### ISSUE THREAD

**Issue by kingulukai** [edwardscamera/array-map-creator#3]
possibile fix:

        try {
            if (map === null) { out = "No canvas to export!" }
            else {
            left_bracket = '[';
            right_bracket = ']';
                switch(document.getElementById('ExpLanguage').value) {
                    case 'javascript':
                        out += 'let arrayMap = [';
                        comment = '// ';
                        break;
                    case 'java':
                        out += 'int[][] arrayMap = {';
                        comment = '// ';
                        left_bracket = '{';
                        right_bracket = '}';
                        break;
                    case 'python':
                        out += 'arrayMap = [';
                        comment = '# ';
                        break;
                }
                for(let i = 0; i < map.length; i++) {
                    if (space && i !== 0) out += "\t";
                    out += left_bracket+`${map[i].toString()}`+right_bracket;
                    out += i === map.length - 1 ? right_bracket : ',';
                    if (space) out += '\n';
                }

**Comment by edlrod** [comment]
@kingulukai Thank you!

Thinking about rewriting this tool from the ground up...
