### ISSUE TITLE
Can't go back after 'Export'

### ISSUE THREAD

**Issue by olinorwell** [edwardscamera/array-map-creator#4]
Great tool thanks for sharing, I've used it this afternoon to great effect.

One issue that I thought I'd mention as I think it's an oversight. Once you've done your design, then clicked on 'Export' to export it, you cannot then return to continue editing your design.

This nearly caught me out, I spent 30 mins doing a design, clicked edit, then decided I wanted to make a tweak. I realised I couldn't get back to the editor.

Fortunately I had taken a copy of the export and was able to use the import function to continue where I left off.

Anyway just wanted to say thanks for creating a neat little tool that helped me out today.

**Comment by edlrod** [comment]
Hi Oli!

Thank you so much for opening this issue. It blows my mind people still use something I made in middle school. I suppose this would be a fun project to rebuild once I have the time.

Until then, I have added a back button you can click on the import/export screens. You may have to empty the cache for it to work.
